spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: ${CB_DB_URL}
    username: ${CB_DB_USER_NAME}
    password: ${CB_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
